slack_api_url = 'https://hooks.slack.com/services/ABCDEFGHI/ABCDEFGHI/abcdefghijklmnopqrstuvwx'
keyhouse_base_url = 'https://api.github.com/repos/sdslabs/keyhouse-template/contents'
keyhouse_token = 'secret_token'
keyhouse_hostname = 'virtual-machine'
